name: MiniGameNpc
version: 1.0
api: [4.0.0]
author: dantedevs
main: Dctx\Entity\Main
description: Dont Work!

permissions:
  nf.cmd:
    description: Permission to all commands
    default: op
    children:
      nf.cmd.help:
        description: Permission for /nf help
        default: op
      nf.cmd.npc:
        description: Permission for /nf npc
        default: op
